kakao:
  apiKey : 7d166971e126d01783f96e1b75fea0ae
  callbackURL : http://localhost:8080/auth/kakao/callback
  # requestURL : https://kauth.kakao.com/oauth/authorize?client_id=7d166971e126d01783f96e1b75fea0ae&redirect_uri=http://localhost:8080/auth/kakao/callback&response_type=code
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url : jdbc:mariadb://localhost:3306/farmily
    username : root
    password : ab3670

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true